#!/usr/bin/env ruby

require './meetups_api'
require 'time'
require 'optparse'
require 'erb'

ICONS = {
  ours: {
    emoji: '🏠',
    image: 'https://mail.google.com/mail/e/4B0'
  },
  attending: {
    emoji: '🌟',
    image: 'https://mail.google.com/mail/e/B68'
  }
}

OPTIONS = {
  blacklist: 'blacklist.txt',
  category: 34,
  city: 'sydney',
  highlight: 'users.yml',
  fast: false
}

OptionParser.new do |opts|
  opts.banner = "Usage: upcoming [options]"

  opts.on('--all', "Don't use a blacklist") { |v| OPTIONS[:all] = v }
  opts.on('--raw', "Raw output, no markdown") { |v| OPTIONS[:raw] = v }
  opts.on('-c', '--city CITY', 'Meetup city (default: Sydney)') { |v| OPTIONS[:city] = v }
  opts.on('-b', '--blacklist FILE', 'Meetup blacklist file (default: blacklist.txt)') { |v| OPTIONS[:blacklist] = v }
  opts.on('--highlight FILE', 'Attendees to highlight (default: users.yml)') { |v| OPTIONS[:highlight] = v }
  opts.on('-f', '--fast', "Don't highlight notable attendees") { |v| OPTIONS[:fast] = v }
  opts.on('--category N', Integer, 'Meetup.com category ID (default: 34)') { |v| OPTIONS[:category] = v }
  opts.on('-v', '--verbose', 'Log debug info') { |v| OPTIONS[:verbose] = v }
  opts.on('--emoji', 'Use emoji for icons') { |v| OPTIONS[:emoji] = v }
end.parse!

def icon(name)
  return ICONS[name][:emoji] if OPTIONS[:emoji]
  "![](#{ICONS[name][:image]})"
end

unless OPTIONS[:all] || File.exist?(OPTIONS[:blacklist])
  puts "Error: Blacklist file not found (#{OPTIONS[:blacklist]})"
  exit(1) 
end

meetups_api = MeetupsApi.new(ENV['API_KEY'], OPTIONS)
meetups = meetups_api.meetups()

if OPTIONS[:raw]
  meetups.each do |m|
    puts "#{m.time}\t#{m.group}\t#{m.notable_attendees}\t#{m.url}"
  end
else
  renderer = ERB.new(File.read 'upcoming.erb')
  puts output = renderer.result()
end
